spring:
  cache:
    type: redis
  redis:
    host: 192.168.93.147
    port: 6379
    password: password
    database: 3
    timeout: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.93.146/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2
  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
mybatis:
  type-aliases-package: com.example.training.domain

